// Refaktor baris kode pada iterasi 1
// Refaktor baris kode pada iterasi 2
// Refaktor baris kode pada iterasi 3
// Refaktor baris kode pada iterasi 4
// Refaktor baris kode pada iterasi 5
// Refaktor baris kode pada iterasi 6
// Refaktor baris kode pada iterasi 7
// Refaktor baris kode pada iterasi 8
// Refaktor baris kode pada iterasi 9
// Refaktor baris kode pada iterasi 10
// Refaktor baris kode pada iterasi 11
// Refaktor baris kode pada iterasi 12
// Refaktor baris kode pada iterasi 13
