// Refaktor baris kode pada iterasi 1
// Refaktor baris kode pada iterasi 2
// Refaktor baris kode pada iterasi 3
// Refaktor baris kode pada iterasi 4
// Refaktor baris kode pada iterasi 5
// Refaktor baris kode pada iterasi 6
// Refaktor baris kode pada iterasi 7
// Refaktor baris kode pada iterasi 8
// Refaktor baris kode pada iterasi 9
// Refaktor baris kode pada iterasi 10
// Refaktor baris kode pada iterasi 11
// Refaktor baris kode pada iterasi 12
// Refaktor baris kode pada iterasi 13
// Refaktor baris kode pada iterasi 14
// Refaktor baris kode pada iterasi 15
// Refaktor baris kode pada iterasi 16
// Refaktor baris kode pada iterasi 17
// Refaktor baris kode pada iterasi 18
// Refaktor baris kode pada iterasi 19
// Refaktor baris kode pada iterasi 20
// Refaktor baris kode pada iterasi 21
// Refaktor baris kode pada iterasi 22
// Refaktor baris kode pada iterasi 23
// Refaktor baris kode pada iterasi 24
// Refaktor baris kode pada iterasi 25
// Refaktor baris kode pada iterasi 26
// Refaktor baris kode pada iterasi 27
// Refaktor baris kode pada iterasi 28
// Refaktor baris kode pada iterasi 29
// Refaktor baris kode pada iterasi 30
// Refaktor baris kode pada iterasi 31
// Refaktor baris kode pada iterasi 32
// Refaktor baris kode pada iterasi 33
